# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "juniorales/dev"
description: > # this means to ignore newlines until "email:"
  tecnologia e desenvolvimento de software

email: edilson.ales.jr@gmail.com
logo: "/assets/images/main-logo.jpg"
cover: true
cover_portrait: "/assets/images/cover-portrait.jpg"
cover_landscape: "/assets/images/cover-landscape.jpg"
timezone: "Americas/Sao_Paulo"
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
destination: "_dist"

name: 'Junior Ales'
author: 'Junior Ales'
author_bio: 'Um desenvolvedor resolvendo problemas de pessoas com código e ideias.'
author_site: 'http://juniorales.com'
author_image: "/assets/images/author.jpg"

paginate: 5

url: "http://juniorales.com"
baseurl: "/dev"
twitter_handle: '@junior_ales'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon: twitter
    url: https://twitter.com/junior_ales
    desc: Siga-me no twitter
    #share_url: http://twitter.com/share
    #share_title: ?text=
    #share_link: "&amp;url="

  - icon: github
    url: https://github.com/junior-ales
    desc: Código aberto que produzo
    share_url:
    share_title:
    share_link:
